var graphs = [
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "behindColumns": true,
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-1",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "5p",
        "type": "column",
        "valueField": "5p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-2",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "15p",
        "type": "column",
        "valueField": "15p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-3",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "25p",
        "type": "column",
        "valueField": "25p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-4",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "35p",
        "type": "column",
        "valueField": "35p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-5",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "45p",
        "type": "column",
        "valueField": "45p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-6",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "50p",
        "type": "column",
        "valueField": "50p",
        "fillColorsField": "Color",
        "lineColorField": "Color"							
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-7",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "55p",
        "type": "column",
        "valueField": "55p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-8",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "65p",
        "type": "column",
        "valueField": "65p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-9",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "75p",
        "type": "column",
        "valueField": "75p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-10",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "85p",
        "type": "column",
        "valueField": "85p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    },
    {
        "alphaField": "Transparency",
        "balloonText": "[[title]] of [[State]]: $[[value]]",
        "fillAlphas": 1,
        "fillColors": "#6899b5",
        "id": "AmGraph-11",
        "lineAlpha": 0.9,
        "lineColor": "#74bee9",
        "title": "95p",
        "type": "column",
        "valueField": "95p",
        "fillColorsField": "Color",
        "lineColorField": "Color"
    }
]